### PR TITLE
:bug: Adding navigation bar color for android

### LINKED ISSUE #217: [Android] Safe area loses background color
Looking at an app like Twitter on Android, you can see the botttm under the Navigation bar is colored white.

However, on CR it's a flat black versus the desired `colors.background`.

Not sure if Screen is the culprit or a top level navigator somewhere

### PR DESCRIPTION
**Pull request by morganick**
# Description

[Trello Card](190-android-safe-area-loses-background-color)
Fixes #217 

The navigationBar color was not set. It is now the beautiful color of `colors.background`.

# Graphics

| Before            | After             |
| -------------- | ------------------ |
| Screenshot_20230510_145845_Chain React App 2023 | Screenshot_20230510_145356_Chain React App 2023 |
| image | image |

# Checklist:

- [x] I have done a thorough self-review of my code
- [ ] I have tested with a screen reader and font-scaling turned on and added necessary accessibility features
- [x] I have run tests and linter

### CODE REVIEW

**Review by mazenchami — COMMENTED** [review]
That's pretty cool. I assume no implications on iOS?

**Comment by morganick** [comment]
@mazenchami I added the iOS screenshots as well. No change to iOS.

**Review by frankcalise — APPROVED** [review]
Awesome! Would be a great upstream contribution to the Demo Nav in Ignite too

**Review by mazenchami — APPROVED** [review]

**Comment by morganick** [comment]
Added to ignite as well: https://github.com/infinitered/ignite/pull/2434

**Pull request merged**
